/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['heart-muscle']: THREE.SkinnedMesh
    Object_30: THREE.SkinnedMesh
    ['right-atrium']: THREE.SkinnedMesh
    GLTF_created_0_rootJoint: THREE.Bone
  }
  materials: {
    ['material_0.001']: THREE.MeshPhysicalMaterial
    material_0: THREE.MeshPhysicalMaterial
  }
}

type ActionName = 'test'

export function HeartModel(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF('/3d-models/heart-cross-new.glb') as GLTFResult

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="RootNode0_0" scale={0.01}>
                <group name="skeletal3_3">
                  <group name="GLTF_created_0">
                    <skinnedMesh
                      name="heart-muscle"
                      geometry={nodes['heart-muscle'].geometry}
                      material={materials['material_0.001']}
                      skeleton={nodes['heart-muscle'].skeleton}
                    />
                    <group name="heart2_2_correction">
                      <group name="heart2_2" />
                    </group>
                    <skinnedMesh
                      name="Object_30"
                      geometry={nodes.Object_30.geometry}
                      material={materials.material_0}
                      skeleton={nodes.Object_30.skeleton}
                    />
                    <skinnedMesh
                      name="right-atrium"
                      geometry={nodes['right-atrium'].geometry}
                      material={materials.material_0}
                      skeleton={nodes['right-atrium'].skeleton}
                    />
                    <group name="right-atrium-int" />
                    <primitive object={nodes.GLTF_created_0_rootJoint} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3d-models/heart-cross-new.glb')
